### ISSUE TITLE
Getting 'InsecureRequestWarning'

### ISSUE THREAD

**Issue by wschlotter** [linuxserver/docker-mylar#14]
When I select a comic and go into the page to link on the issues, they never load. When looking at the log i get the following, and this is all that loads.

/app/mylar/lib/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

Distributor ID:	Ubuntu
Release:	16.04
Codename: xenial
4.4.0-96-generic GNU/Linux

docker create \
  -p 8090:8090\
  --name=mylar \
  -v /etc/localtime:/etc/localtime:ro \
  -v ~/.config/mylar:/config \
  -v ~/misc_media/comics:/comics \
  -v ~/downloads:/downloads \
  -e PGID=1000 \
  -e PUID=1000 \
  linuxserver/mylar

container-name = mylar

**Comment by vader083** [comment]
Seeing this as well

**Comment by sparklyballs** [comment]
this looks to be an upstream issue with mylar to me.

[the lib is there and provided as part of mylar](https://github.com/evilhero/mylar/tree/master/lib/requests/packages/urllib3), but according to that link, either it is not a secure version or some additional code is required by the app itself.
