### ISSUE TITLE
Could not locate exceptions.csv file

### ISSUE THREAD

**Issue by ubun2Junky** [linuxserver/docker-mylar#16]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Host OS:  Ubuntu 18.04
Mylar Log Output:
`21-May-2018 14:05:43 - ERROR   :: mylar.csv_load.1079 : MainThread : Could not locate exceptions.csv file. Make sure it is in datadir: /config/mylar`

Not sure why the exceptions.csv, _sample.csv and custom_exceptions.csv files were not created when the container first generated all the other configurations.  The errors resolved themselves when I manually entered into the container and manually moved the files to my configuration directory.

**Comment by sparklyballs** [comment]
this is a harmless warning.

if you want exceptions (and understand the logic, lol) you can create your own file based on the one in the /apps folder.
