### ISSUE TITLE
2018-06-08 Push Caused New Warning

### ISSUE THREAD

**Issue by LeeThompson** [linuxserver/docker-mylar#17]
The linuxserver.io mylar container published 2018-06-08 15:10:24 with `sha256:2176dc52bd24984ee650e09717f7013fdff8be420e7d26dcf02bb66b80edba2f` contains a library that Mylar is not happy about.    

`2018-06-09 10:39:29 | DEBUG | [META-TAGGER] /usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version! being used - using personal ComicVine API key supplied via mylar.`

**Comment by LeeThompson** [comment]
The author of Mylar has done some updates which may help this issue.

**Comment by homerr** [comment]
Closing this off as stale, but if the issue has persisted since the update from the author, please re-open and we can have a look.
