### ISSUE TITLE
FeatureNotFound error in logs

### ISSUE THREAD

**Issue by partymike** [linuxserver/docker-mylar#20]
thanks for this container, but could you add the following to stop this error showing in logs:

"FeatureNotFound﻿: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?"

To resolve I run:

"docker exec -it mylar /bin/bash"

then

"pip install html5lib"

Which fix's the issue and allows a better torrent search if you have that setup in mylar.

Much appreciated :-)

**Comment by sparklyballs** [comment]
package is in the image as of 6th july 2018.

closing this.
