### ISSUE TITLE
Missing Node.js

### ISSUE THREAD

**Issue by SenorSmartyPants** [linuxserver/docker-mylar#24]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Armbian armhf

##  Thanks, team linuxserver.io

Mylar generates errors when trying to communicate with the new WWT site. I manually updated the WWT URL in my install (since it is only updated in dev github) but once it points to new site errors like the following occur.

> [WWT-RSSFEED] Unable to retrieve RSS properly: Missing Node.js runtime. Node is required and must be in the PATH (check with `node -v`). Your Node binary may be called `nodejs` rather than `node`, in which case you may need to run `apt-get install nodejs-legacy` on some Debian-based systems. (Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies.

Please install node.js on all mylar dockers. Thank you.

**Comment by vader083** [comment]
I'm hitting this as well with [32P-AUTHENTICATION]

**Comment by thelamer** [comment]
Was not aware of this requirement will have some PRs shortly 
Is there anything we can do to simplify this setup or is this URL not a standard thing ?

**Comment by thelamer** [comment]
@SenorSmartyPants @vader083 PR created awaiting merge https://github.com/linuxserver/docker-mylar/pull/27

**Comment by vader083** [comment]
Thanks! working now
