### ISSUE TITLE
Error on start up [ARMv6] missing html5lib?

### ISSUE THREAD

**Issue by SenorSmartyPants** [linuxserver/docker-mylar#25]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Armbian
Linux servername 4.14.70-sunxi #265 SMP Wed Sep 19 10:01:19 CEST 2018 armv7l GNU/Linux

> mylar            | 2019-01-17T18:09:10.190105191Z Initializing startup sequence....
> mylar            | 2019-01-17T18:09:10.192833610Z     self.__target(*self.__args, **self.__kwargs)
> mylar            | 2019-01-17T18:09:10.193683088Z   File "/app/mylar/mylar/helpers.py", line 3059, in search_queue
> mylar            | 2019-01-17T18:09:10.206050072Z     ss_queue = mylar.search.searchforissue(item['issueid'])
> mylar            | 2019-01-17T18:09:10.207272271Z   File "/app/mylar/mylar/search.py", line 1822, in searchforissue
> mylar            | 2019-01-17T18:09:10.214538556Z     foundNZB, prov = search_init(ComicName, IssueNumber, str(IssueYear), SeriesYear, Publisher, IssueDate, StoreDate, actissueid, AlternateSearch, UseFuzzy, ComicVersion, SARC=SARC, IssueArcID=IssueArcID, mode=mode, rsscheck=rsscheck, ComicID=ComicID, filesafe=Comicname_filesafe, allow_packs=allow_packs, oneoff=oneoff, manual=manual, torrentid_32p=TorrentID_32p, digitaldate=DigitalDate, booktype=booktype)
> mylar            | 2019-01-17T18:09:10.215818627Z   File "/app/mylar/mylar/search.py", line 353, in search_init
> mylar            | 2019-01-17T18:09:10.218971180Z     findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, RSS="no", ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName, allow_packs=allow_packs, oneoff=oneoff, cmloopit=cmloopit, manual=manual, torznab_host=torznab_host, torrentid_32p=torrentid_32p, digitaldate=digitaldate, booktype=booktype)
> mylar            | 2019-01-17T18:09:10.221290672Z   File "/app/mylar/mylar/search.py", line 660, in NZB_SEARCH
> mylar            | 2019-01-17T18:09:10.227258180Z     bb = ww.wwt_connect()
> mylar            | 2019-01-17T18:09:10.227502079Z   File "/app/mylar/mylar/wwt.py", line 57, in wwt_connect
> mylar            | 2019-01-17T18:09:10.227608737Z     soup = BeautifulSoup(r.content, "html5lib")
> mylar            | 2019-01-17T18:09:10.231670931Z   File "/app/mylar/lib/bs4/__init__.py", line 165, in __init__
> mylar            | 2019-01-17T18:09:10.231902497Z     % ",".join(features))
> mylar            | 2019-01-17T18:09:10.231988199Z bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

Is html5lib missing from image?

**Comment by thelamer** [comment]
@SenorSmartyPants PR created awaiting merge https://github.com/linuxserver/docker-mylar/pull/27
