### ISSUE TITLE
"You're running an unknown version of Mylar. Update or Close" message is displayed.

### ISSUE THREAD

**Issue by SenorSmartyPants** [linuxserver/docker-mylar#26]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Armbian
Linux servername 4.14.70-sunxi #265 SMP Wed Sep 19 10:01:19 CEST 2018 armv7l GNU/Linux

Mylar runs but displays a yellow popup with the text in the issue title. If you go to settings it does not display which git branch is installed or the versions checksum.

Mylar should display what version of the app is running somewhere.

The https://hub.docker.com/r/lsioarmhf/mylar version has always displayed this information. But the https://hub.docker.com/r/linuxserver/mylar version does not.

**Comment by thelamer** [comment]
We are shifting across the board to not directly supporting updating in a container as these are tagged to commits at head and we curl that specific commit in at build time. 
I understand this pops up, but a developer depending on an entire git tree to be present to determine versioning is not something we are going to support moving forward on main line builds. 
Optimally this project should shift to release tagging in Github and not have users running at Head. 
I understand this is not the answer you are looking for, but we try to keep images as lean as possible and use docker to handle upgrading.
