### ISSUE TITLE
Update urllib and chardet

### ISSUE THREAD

**Issue by SenorSmartyPants** [linuxserver/docker-mylar#33]
This fork has the fixes required (not the development branch, but if you wanted to do that I wouldn't mind)

https://github.com/linuxserver/docker-mylar/compare/master...misleadingrhino:master#diff-3254677a7917c6c01f55212f86c57fbf

Please check out this post for details - https://forum.mylarcomics.com/viewtopic.php?p=10913&sid=bf1053f99a1f300014b14a75827f5e51#p10913

**Comment by thelamer** [comment]
So what you are saying is the following pip modules need to be added for post processing to work properly: 
```
'urllib3<1.25' 
chardet
requests
```
Right?

**Comment by SenorSmartyPants** [comment]
I think that is correct. I thought requests might already be installed, but am unsure.

**Comment by sparklyballs** [comment]
All 3 packages are installed. Urllib however needs downgrading from the current version using the less than 1.25

**Comment by thedeany** [comment]
I'm encountering this issue as well. Let me know if you need any specific further details.

**Comment by francispeixoto** [comment]
I have the issue as well. it seems that every time watchtower deploys a new version of the image, I have to do this in the container (`docker exec -it mylar /bin/bash`) to resolve the issue with comictagger.py in the post-processing tasks:

```
pip uninstall requests
pip install requests
```

once it's reinstalled, the post-processing executes successfully.

EDIT: Specified that I do this within the container itself
