### ISSUE TITLE
Startup error when http_host is set: Failed to start on port: 8090. Is something else running?

### ISSUE THREAD

**Issue by lhilton** [linuxserver/docker-mylar#35]
When I launch the docker of mylar (see below for launch command), I cannot launch of the configuration value for `http_host` is my hostname instead of `0.0.0.0`. The error is noted in the below docker log output. I have confirmed that nothing else is running on this port. I can change the `http_host` value back to `0.0.0.0` and then restart the docker (not the server) and it comes up just fine.

My primary need is to get this working behind traefik as a reverse proxy. If there is a way to go about this without setting the `http_host` value then I am willing to try another approach, but the docs and my experience indicates that this is necessary to get the reverse proxy to work. Otherwise mylar wants to redirect to the internal docker IP of the host system when I try to access off of the hostname.

### Host OS:
**Ubuntu 18.04**

### Command line users, your run/create command, GUI/Unraid users, a screenshot of your template settings.
```
docker run -itd \
    --name=a.mylar \
    --restart always \
    -v /storage/mylar:/config \
    -v /storage/downloads:/downloads \
    -v /storage/nfs-cloud-drive/comics:/comics \
    -e TZ="America/Los_Angeles" \
    -e PGID=911 -e PUID=911  \
    -p 8090:8090 \
    linuxserver/mylar:latest
```

### Docker log output, docker log <container-name>
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom scripts found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
log language set to en_US
Quiet logging mode enabled...
Initializing startup sequence....
Failed to start on port: 8090. Is something else running?
```

### Mention if you're using symlinks on any of the volume mounts.
**No**

**Comment by thelamer** [comment]
If you are are combining container networks they can conflict on the internal ports. 
Something inside these docker networks is listening on 8090 and thus why it cannot bind to it , you can run something like 
```
netstat -tunlap
```
inside your containers to determine what that could be. 

In any case I appreciate the detailed information, but I do not believe this issue is a bug report of feature request specific to the Mylar container. 
If you need further assistance please hop on our discord: 

https://discord.gg/YWrKVTn

**Comment by lhilton** [comment]
As I noted in my note:

> I have confirmed that nothing else is running on this port.

I can also change the port to other ports (18090 for example) in the config.ini file and the error message persists (updating the port listed to the configured value as well).

I should note: I have isolated this behavior on a machine with a fresh install of Ubuntu 18.04 server, docker installed per the docker websites getting-started guide. **There are no other docker containers running on this machine presently**.

I do **not** get this behavior if I just install mylar outside of docker on my local.

I do not, however, know what you mean when you say:

> If you are are combining container networks they can conflict on the internal ports.

Is there something in my run command that I should adjust? As I noted, this is on a vanilla install of my stack.

**Comment by thelamer** [comment]
The general gist of my message is that this is really not the forum for support . You should not be changing the internal port for any reason.
We do test these images https://lsio-ci.ams3.digitaloceanspaces.com/linuxserver/mylar/latest/index.html and I have confirmed locally that it works. 
So it has to be your local setup. 
Please leverage our community on Discord it is possible someone has run into an issue like this before .
