### ISSUE TITLE
Mylar3 - New Docker?

### ISSUE THREAD

**Issue by MEGAMENE** [linuxserver/docker-mylar#39]
Hi, I've just saw that the old Mylar project has stopped development and all efforts have moved over to [Mylar3](https://github.com/mylar3/mylar3).
I don't know if the best option would be to just update this docker project or create a new one, but something should be done before they decide to EOL the old project, thanks.

**Comment by aptalca** [comment]
Thanks for the heads up. I guess we'll have to look into whether we should update this image to pull from the new repo or create a new mylar3 image.

**Comment by CHBMB** [comment]
At the moment Mylar3 looks to be an alpha project, so not sure if we should migrate this one or consider it a separate entity in terms of either a branch or fresh repository.

**Comment by thelamer** [comment]
We should go new, given the codebase it should be relatively low maintenance to keep the packages up to date on this legacy container and sunset it down the line. 
But yeah it does not look like mylar3 is ready yet.

**Comment by theotocopulitos** [comment]
Any updates on this? As per the author’s words, mylar3 is now the current Mylar, and development is stopped in Mylar v2...

Thanks

**Comment by aptalca** [comment]
There is a new repo for a [WIP image](https://github.com/linuxserver/docker-mylar3/tree/initial), but since I could not get it to work locally (gui comes up, downloads are sent, but post-processing did not work), there hasn't been much development after the initial push.

**Comment by aptalca** [comment]
Mylar3 published: https://github.com/linuxserver/docker-mylar3
