### ISSUE TITLE
Mylar NZB sending to SAB broken

### ISSUE THREAD

**Issue by icebal** [linuxserver/docker-mylar#5]
when Mylar snatches an NZB, it sends sab an URL back to Mylar to upload the nzb. the issue with this is Mylar sends sab the docker ip address instead of something sab can actually connect to. the work around for right now is to setup black hole for sab, net=privileged , or link the containers together. the url given to sab as an example is:

Trying to fetch NZB from https://CONTAINERIP:8090/api?apikey=APIKEY&cmd=downloadNZB&nzbname=COMICBOOKNAME.nzb

**Comment by lonix** [comment]
Try useing the host ip rather than the container ip
fre. 11. mar. 2016 kl. 17.17 skrev wesley jackson <notifications@github.com

**Comment by icebal** [comment]
setting the ip to the host IP or hostname removes access to the webGUI, as does using anything other than 0.0.0.0. This is more of a mylar bug inside Docker, but still is an issue.

**Comment by icebal** [comment]
Link to the issue on mylar's github:
https://github.com/evilhero/mylar/issues/1094

**Comment by sparklyballs** [comment]
read the response from evilhero posted since your reply.

**Comment by icebal** [comment]
Comment from the above link, for future reference:
You probably need to use the host_return option within the config.ini for mylar. Set it to the direct ip of your mylar installation, so that if you were trying to load something from mylar within sabnzbd it can be reached:
host_return = http://192.168.1.10:8090/

You can then leave the actual host address within mylar as 0.0.0.0 (or local host) and it will force sabnzbd to request the nzb360.com from the host_return ip when trying to grab the nzbs from mylar.

**Comment by hashmil** [comment]
I had the same issue. Can confirm that the below from @icebal is the definite fix (at least for me!)

"You probably need to use the host_return option within the config.ini for mylar. Set it to the direct ip of your mylar installation, so that if you were trying to load something from mylar within sabnzbd it can be reached:
host_return = http://192.168.1.10:8090/"
